

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"

export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT"
