

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"

export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"

export const SELECT_PRODUCT_TO_EDIT = "SELECT_PRODUCT_TO_EDIT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT"
